In [83]:
import numpy as np

In [84]:
def split_sequence(seq, n_steps):
    
    x = []
    y = []
    
    for i in range(len(seq)):
        last_index = i + n_steps
        
        if last_index > len(seq) - 1:
            break
        
        seq_x, seq_y = seq[i:last_index], seq[last_index]
        
        x.append(seq_x)
        y.append(seq_y)
        
        pass
    
    x = np.array(x, dtype=np.float32)
    y = np.array(y, dtype=np.float32)
    
    return x,y
    
    pass
        

In [85]:
# 13 first fibonacci numbers
data = [1,1,2,3,5,8,13,21,34,55,89,144,233]
n_steps = 5
x, y = split_sequence(data, n_steps)

In [86]:
for i in range(len(x)):
    print(x[i], y[i])

[1. 1. 2. 3. 5.] 8.0
[1. 2. 3. 5. 8.] 13.0
[ 2.  3.  5.  8. 13.] 21.0
[ 3.  5.  8. 13. 21.] 34.0
[ 5.  8. 13. 21. 34.] 55.0
[ 8. 13. 21. 34. 55.] 89.0
[13. 21. 34. 55. 89.] 144.0
[ 21.  34.  55.  89. 144.] 233.0


In [87]:
# LSTM need input of the form [batch, timesteps, features]
# hence we need to shape the the data x
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))
print(x[:2])

[[[1.]
  [1.]
  [2.]
  [3.]
  [5.]]

 [[1.]
  [2.]
  [3.]
  [5.]
  [8.]]]


In [129]:
# Create model
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [130]:
model.layers

In [131]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [132]:
# Compile the model
model.compile(
            optimizer=tf.keras.optimizers.Adam(0.01), 
            loss=tf.keras.losses.MeanSquaredError(), 
            metrics=['accuracy']
)

In [133]:
# Train the model
model.fit(x, y, epochs=200, verbose=1)

Train on 8 samples
Epoch 1/200
8/8 [==============================] - 2s 286ms/sample - loss: 10415.5195 - accuracy: 0.0000e+00
Epoch 2/200
8/8 [==============================] - 0s 2ms/sample - loss: 9903.9609 - accuracy: 0.0000e+00
Epoch 3/200
8/8 [==============================] - 0s 2ms/sample - loss: 9368.1660 - accuracy: 0.0000e+00
Epoch 4/200
8/8 [==============================] - 0s 3ms/sample - loss: 8766.3896 - accuracy: 0.0000e+00
Epoch 5/200
8/8 [==============================] - 0s 3ms/sample - loss: 8052.0244 - accuracy: 0.0000e+00
Epoch 6/200
8/8 [==============================] - 0s 2ms/sample - loss: 6954.8198 - accuracy: 0.0000e+00
Epoch 7/200
8/8 [==============================] - 0s 3ms/sample - loss: 4036.3003 - accuracy: 0.0000e+00
Epoch 8/200
8/8 [==============================] - 0s 2ms/sample - loss: 123.0043 - accuracy: 0.0000e+00
Epoch 9/200
8/8 [==============================] - 0s 2ms/sample - loss: 2139.9565 - accuracy: 0.0000e+00
Epoch 10/200
8/8 [=======

Epoch 79/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.3021 - accuracy: 0.0000e+00
Epoch 80/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.1961 - accuracy: 0.0000e+00
Epoch 81/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.1604 - accuracy: 0.0000e+00
Epoch 82/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.1946 - accuracy: 0.0000e+00
Epoch 83/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.2483 - accuracy: 0.0000e+00
Epoch 84/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.2666 - accuracy: 0.0000e+00
Epoch 85/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.2309 - accuracy: 0.0000e+00
Epoch 86/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.1683 - accuracy: 0.0000e+00
Epoch 87/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.1234 - accuracy: 0.0000e+00
Epoch 88/200
8/8 [==============================] - 0s 2ms/sampl

Epoch 158/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0397 - accuracy: 0.0000e+00
Epoch 159/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0396 - accuracy: 0.0000e+00
Epoch 160/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0395 - accuracy: 0.0000e+00
Epoch 161/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0394 - accuracy: 0.0000e+00
Epoch 162/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0393 - accuracy: 0.0000e+00
Epoch 163/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0392 - accuracy: 0.0000e+00
Epoch 164/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0391 - accuracy: 0.0000e+00
Epoch 165/200
8/8 [==============================] - 0s 3ms/sample - loss: 0.0390 - accuracy: 0.0000e+00
Epoch 166/200
8/8 [==============================] - 0s 4ms/sample - loss: 0.0390 - accuracy: 0.0000e+00
Epoch 167/200
8/8 [==============================] - 0s

In [134]:
# Predictions
test_data = np.array([89,144,233,377,610], dtype=np.float32)
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 89.],
        [144.],
        [233.],
        [377.],
        [610.]]], dtype=float32)

In [135]:
predict_next_fib = model.predict(test_data, verbose=1)
print(predict_next_fib)

1/1 [==============================] - 0s 397ms/sample
[[988.073]]


In [136]:
test_data = np.array([377,610,987,1597,2584], dtype=np.float32)
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 377.],
        [ 610.],
        [ 987.],
        [1597.],
        [2584.]]], dtype=float32)

In [137]:
predict_next_fib = model.predict(test_data, verbose=1)
print(predict_next_fib)

1/1 [==============================] - 0s 4ms/sample
[[4178.7344]]
