In [1]:
import numpy as np

In [2]:
def split_sequence(seq, n_steps):
    
    x,y = [], []
    
    for i in range(len(seq)):
        last_index = i + n_steps
        
        if last_index > len(seq) - 1:
            break
        
        seq_x, seq_y = seq[i:last_index], seq[last_index]
        
        x.append(seq_x)
        y.append(seq_y)
    
    x = np.array(x, dtype=np.float32)
    y = np.array(y, dtype=np.float32)
    
    return x,y

In [3]:
# 13 first fibonacci numbers
data = [1,1,2,3,5,8,13,21,34,55,89,144,233]
n_steps = 5
x, y = split_sequence(data, n_steps)

In [4]:
def F(n):
    if n == 0: 
        return 0
    elif n == 1: 
        return 1
    else: 
        return F(n - 1) + F(n - 2)

In [5]:
for i in range(len(x)):
    print(x[i], y[i])

[1. 1. 2. 3. 5.] 8.0
[1. 2. 3. 5. 8.] 13.0
[ 2.  3.  5.  8. 13.] 21.0
[ 3.  5.  8. 13. 21.] 34.0
[ 5.  8. 13. 21. 34.] 55.0
[ 8. 13. 21. 34. 55.] 89.0
[13. 21. 34. 55. 89.] 144.0
[ 21.  34.  55.  89. 144.] 233.0


In [6]:
# LSTM need input of the form [batch, timesteps, features]
# hence we need to shape the the data x
n_features = 1
x = x.reshape((x.shape[0], x.shape[1], n_features))
print(x[:2])

[[[1.]
  [1.]
  [2.]
  [3.]
  [5.]]

 [[1.]
  [2.]
  [3.]
  [5.]
  [8.]]]


In [7]:
# Create model
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

2022-01-22 14:14:05.325961: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-22 14:14:05.326153: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [8]:
model.layers

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 50)                10400     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [10]:
# Compile the model
model.compile(
            optimizer=tf.keras.optimizers.Adam(0.01), 
            loss=tf.keras.losses.MeanSquaredError(), 
            metrics=['accuracy']
)

In [11]:
# Train the model
model.fit(x, y, epochs=200, verbose=1)

Train on 8 samples
Epoch 1/200
8/8 [==============================] - 2s 294ms/sample - loss: 12501.9443 - accuracy: 0.0000e+00
Epoch 2/200
8/8 [==============================] - 0s 2ms/sample - loss: 11122.3730 - accuracy: 0.0000e+00
Epoch 3/200
8/8 [==============================] - 0s 2ms/sample - loss: 10193.1270 - accuracy: 0.0000e+00
Epoch 4/200
8/8 [==============================] - 0s 4ms/sample - loss: 9522.9023 - accuracy: 0.0000e+00
Epoch 5/200
8/8 [==============================] - 0s 2ms/sample - loss: 8503.4492 - accuracy: 0.0000e+00
Epoch 6/200
8/8 [==============================] - 0s 2ms/sample - loss: 6581.1357 - accuracy: 0.0000e+00
Epoch 7/200
8/8 [==============================] - 0s 2ms/sample - loss: 3793.2510 - accuracy: 0.0000e+00
Epoch 8/200
8/8 [==============================] - 0s 3ms/sample - loss: 1558.7727 - accuracy: 0.0000e+00
Epoch 9/200
8/8 [==============================] - 0s 2ms/sample - loss: 49.3194 - accuracy: 0.0000e+00
Epoch 10/200
8/8 [======

8/8 [==============================] - 0s 2ms/sample - loss: 0.1218 - accuracy: 0.0000e+00
Epoch 80/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0610 - accuracy: 0.0000e+00
Epoch 81/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0347 - accuracy: 0.0000e+00
Epoch 82/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0737 - accuracy: 0.0000e+00
Epoch 83/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0911 - accuracy: 0.0000e+00
Epoch 84/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0542 - accuracy: 0.0000e+00
Epoch 85/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0331 - accuracy: 0.0000e+00
Epoch 86/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.0561 - accuracy: 0.0000e+00
Epoch 87/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0722 - accuracy: 0.0000e+00
Epoch 88/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0

Epoch 158/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.0198 - accuracy: 0.0000e+00
Epoch 159/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0197 - accuracy: 0.0000e+00
Epoch 160/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.0197 - accuracy: 0.0000e+00
Epoch 161/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0196 - accuracy: 0.0000e+00
Epoch 162/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.0196 - accuracy: 0.0000e+00
Epoch 163/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0195 - accuracy: 0.0000e+00
Epoch 164/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0195 - accuracy: 0.0000e+00
Epoch 165/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0194 - accuracy: 0.0000e+00
Epoch 166/200
8/8 [==============================] - 0s 2ms/sample - loss: 0.0194 - accuracy: 0.0000e+00
Epoch 167/200
8/8 [==============================] - 0s

In [12]:
# Predictions
test_data = np.array([89,144,233,377,610], dtype=np.float32)
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 89.],
        [144.],
        [233.],
        [377.],
        [610.]]], dtype=float32)

In [15]:
# Predicting the 16th number
predict_next_fib = model.predict(test_data, verbose=1)
print(predict_next_fib)

converted = [[int(num) for num in sub] for sub in predict_next_fib]

flat_list = [item for sublist in converted for item in sublist]

strings = [str(integer) for integer in flat_list]
a_string = "".join(strings)
predicted_fib = int(a_string)

print(predicted_fib)

1/1 [==============================] - 0s 5ms/sample
[[988.829]]
988


In [16]:
# The correct 16th fibonacci number
F(16)

987

In [19]:
# The difference from the predicted fibonacci number and the correct
print("Difference is", abs(predicted_fib - F(16)))

Difference is 1 integer


In [23]:
test_data_1 = np.array([377,610,987,1597,2584], dtype=np.float32)
test_data_1 = test_data_1.reshape((1, n_steps, n_features))
test_data_1

array([[[ 377.],
        [ 610.],
        [ 987.],
        [1597.],
        [2584.]]], dtype=float32)

In [28]:
# Predicting the 19th number
predict_next_fib_1 = model.predict(test_data_1, verbose=1)
print(predict_next_fib_1)

converted_1 = [[int(num) for num in sub] for sub in predict_next_fib_1]

flat_list_1 = [item for sublist in converted_1 for item in sublist]

strings_1 = [str(integer) for integer in flat_list_1]
a_string_1 = "".join(strings_1)
predicted_fib_1 = int(a_string_1)

print(predicted_fib_1)

1/1 [==============================] - 0s 5ms/sample
[[4206.6167]]
4206


In [27]:
# The correct 19th fibonacci number
F(19)

4181

In [30]:
# The difference from the predicted fibonacci number and the correct
print("Difference is", abs(predicted_fib_1 - F(19)))

Difference is 25
